### ISSUE TITLE
how can support table?

### ISSUE THREAD

**Issue by dongodngtang** [tradle/rn-markdown#1]
how can support table?

**Comment by mvayngrib** [comment]
see how [List](https://github.com/tradle/rn-markdown/blob/master/markdown.js#L43) is defined. You can create a renderer for table (e.g. call it `Table`), then add a mapping [here](https://github.com/tradle/rn-markdown/blob/master/markdown.js#L75):  `table: Table`

**Comment by dongodngtang** [comment]
Thx,谢谢
