### ISSUE TITLE
Release parser as own module

### ISSUE THREAD

**Issue by MrLoh** [tradle/rn-markdown#3]
Thanks a lot for the great work. I moved away from react-native-simple-markdown because of the shitty parser, that creates all kind of weird errors. But I prefer to just implement my own renderer as I have a very custom setup and there is more overhead in understanding another renderer than just writing a completely custom one. 

On the search for a decent markdown parser that outputs an AST, I was surprised to not find anything until I stumbled on your package. I’m just importing the parser from here now, but it would probably be better to have a separate module for this great parser. Would also be nice if there was an option to turn off the parent links, as they prevent calling JSON.stringify on the parser output.

**Comment by mvayngrib** [comment]
thanks, it's mostly thanks to the great work by @chjj in [marked](https://github.com/chjj/marked)

i'm happy to separate the parser into a separate module if you want to send a PR there? 

re: the parent thing, we can always make it a constructor option

**Comment by mvayngrib** [comment]
@MrLoh I copied the parser out to: https://github.com/tradle/rn-markdown-parser

happy to accept PRs there :)
